export const COLORS_LIGHT = {
	WHITE: '#FFFFFF',
	BLACK: '#000000',

	ERROR_DARK: '#ED3241',
	ERROR_MEDIUM: '#FF616D',
	ERROR_LIGHT: '#FFE2E5',

	SUCCESS_DARK: '#298267',
	SUCCESS_MEDIUM: '#3AC0A0',
	SUCCESS_LIGHT: '#E7F4E8',

	WARNING_DARK: '#E86339',
	WARNING_MEDIUM: '#FFB37C',
	WARNING_LIGHT: '#FFF4E4',

	HIGHLIGHT_DARKEST: '#006FFD',
	HIGHLIGHT_DARK: '#2897FF',
	HIGHLIGHT_MEDIUM: '#6FBAFF',
	HIGHLIGHT_LIGHT: '#B4DBFF',
	HIGHLIGHT_LIGHTEST: '#EAF2FF',

	HIGHLIGHT_DARKEST_INVERSE: '#006FFD',
	HIGHLIGHT_DARK_INVERSE: '#2897FF',
	HIGHLIGHT_MEDIUM_INVERSE: '#6FBAFF',
	HIGHLIGHT_LIGHT_INVERSE: '#B4DBFF',
	HIGHLIGHT_LIGHTEST_INVERSE: '#EAF2FF',

	NEUTRAL_DARK_DARKEST: '#1F2024',
	NEUTRAL_DARK_DARK: '#2F3036',
	NEUTRAL_DARK_MEDIUM: '#494A50',
	NEUTRAL_DARK_LIGHT: '#71727A',
	NEUTRAL_DARK_LIGHTEST: '#8F9098',

	NEUTRAL_LIGHT_DARKEST: '#C5C6CC',
	NEUTRAL_LIGHT_DARK: '#D4D6DD',
	NEUTRAL_LIGHT_MEDIUM: '#E8E9F1',
	NEUTRAL_LIGHT_LIGHT: '#F8F9FE',
	NEUTRAL_LIGHT_LIGHTEST: '#FFFFFF',
};

export const COLORS_DARK = {
	ERROR_DARK: '#ED3241',
	ERROR_MEDIUM: '#FF616D',
	ERROR_LIGHT: '#FFE2E5',

	SUCCESS_DARK: '#298267',
	SUCCESS_MEDIUM: '#3AC0A0',
	SUCCESS_LIGHT: '#E7F4E8',

	WARNING_DARK: '#E86339',
	WARNING_MEDIUM: '#FFB37C',
	WARNING_LIGHT: '#FFF4E4',

	HIGHLIGHT_DARKEST: '#006FFD',
	HIGHLIGHT_DARK: '#2897FF',
	HIGHLIGHT_MEDIUM: '#6FBAFF',
	HIGHLIGHT_LIGHT: '#B4DBFF',
	HIGHLIGHT_LIGHTEST: '#EAF2FF',

	HIGHLIGHT_DARKEST_INVERSE: '#EAF2FF',
	HIGHLIGHT_DARK_INVERSE: '#B4DBFF',
	HIGHLIGHT_MEDIUM_INVERSE: '#6FBAFF',
	HIGHLIGHT_LIGHT_INVERSE: '#2897FF',
	HIGHLIGHT_LIGHTEST_INVERSE: '#006FFD',

	NEUTRAL_LIGHT_DARKEST: '#8F9098',
	NEUTRAL_LIGHT_DARK: '#71717A',
	NEUTRAL_LIGHT_MEDIUM: '#494A50',
	NEUTRAL_LIGHT_LIGHT: '#2F3036',
	NEUTRAL_LIGHT_LIGHTEST: '#000000',

	NEUTRAL_DARK_DARKEST: '#FFFFFF',
	NEUTRAL_DARK_DARK: '#F8F9FE',
	NEUTRAL_DARK_MEDIUM: '#E8E9F1',
	NEUTRAL_DARK_LIGHT: '#D4D6DD',
	NEUTRAL_DARK_LIGHTEST: '#C5C6CC',
};
