name: Build and Release APK

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set up Expo CLI
      run: npm install -g @expo/cli
      
    - name: Set up EAS CLI
      run: npm install -g eas-cli
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android keystore
      run: |
        # Create android directory
        mkdir -p android
        
        # Decode the keystore from GitHub secrets with better error handling
        echo "Decoding keystore from base64..."
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | tr -d '\n\r' | base64 -d > android/recitativos-release.keystore
        
        # Verify keystore file integrity
        if [ -f "android/recitativos-release.keystore" ]; then
          echo "✅ Keystore file created"
          echo "Keystore file size: $(wc -c < android/recitativos-release.keystore) bytes"
          
          # Test keystore with keytool
          echo "Testing keystore integrity..."
          if keytool -list -keystore android/recitativos-release.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -v > /dev/null 2>&1; then
            echo "✅ Keystore is valid and readable"
          else
            echo "❌ Keystore test failed - regenerating keystore may be needed"
            exit 1
          fi
        else
          echo "❌ Failed to create keystore file"
          exit 1
        fi
        
        echo "✅ Keystore setup complete"
        
    - name: Configure EAS Project
      run: |
        # Initialize EAS project (create if doesn't exist)
        echo "Initializing EAS project..."
        eas project:init --non-interactive --force
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build APK
      run: |
        echo "Building APK with environment variables..."
        echo "Current directory contents:"
        ls -la
        echo ""
        echo "Starting APK build..."
        eas build --platform android --profile production --local --output ./build.apk --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        EXPO_ANDROID_KEYSTORE_PATH: ./android/recitativos-release.keystore
        EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        EXPO_ANDROID_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        
    - name: Get tag name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
        name: ${{ steps.get_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false
        files: ./build.apk
        body: |
          ## Release ${{ steps.get_tag.outputs.TAG_NAME }}
          
          This release contains the APK file for Recitativos CCB app.
          
          ### Installation
          Download the APK file and install it on your Android device.
          
          ### Changes
          - Built from tag: ${{ steps.get_tag.outputs.TAG_NAME }}
          - Commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
