name: Build and Release APK

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set up Expo CLI
      run: npm install -g @expo/cli
      
    - name: Set up EAS CLI
      run: npm install -g eas-cli
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android keystore
      run: |
        # Create android directory
        mkdir -p android
        
        # Decode the keystore from GitHub secrets
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/recitativos-release.keystore
        
        # Create credentials.json file with proper variable substitution
        KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}"
        KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
        KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
        
        # Create credentials.json using printf for better control
        printf '{\n  "android": {\n    "keystore": {\n      "keystorePath": "android/recitativos-release.keystore",\n      "keystorePassword": "%s",\n      "keyAlias": "%s",\n      "keyPassword": "%s"\n    }\n  }\n}' "$KEYSTORE_PASSWORD" "$KEY_ALIAS" "$KEY_PASSWORD" > credentials.json
        
        # Verify files were created
        if [ -f "android/recitativos-release.keystore" ]; then
          echo "✅ Keystore decoded successfully"
          ls -la android/
        else
          echo "❌ Failed to decode keystore"
          exit 1
        fi
        
        if [ -f "credentials.json" ]; then
          echo "✅ Credentials file created successfully"
          echo "Credentials file structure (passwords hidden):"
          cat credentials.json | sed 's/"Password": "[^"]*"/"Password": "***"/g'
          echo ""
          echo "File permissions:"
          ls -la credentials.json
        else
          echo "❌ Failed to create credentials file"
          exit 1
        fi
        
    - name: Configure EAS Project
      run: |
        # Initialize EAS project (create if doesn't exist)
        echo "Initializing EAS project..."
        eas project:init --non-interactive --force
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build APK
      run: |
        echo "Building APK with local credentials..."
        echo "Current directory contents:"
        ls -la
        echo ""
        echo "Starting APK build..."
        eas build --platform android --profile production --local --output ./build.apk --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Get tag name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
        name: ${{ steps.get_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false
        files: ./build.apk
        body: |
          ## Release ${{ steps.get_tag.outputs.TAG_NAME }}
          
          This release contains the APK file for Recitativos CCB app.
          
          ### Installation
          Download the APK file and install it on your Android device.
          
          ### Changes
          - Built from tag: ${{ steps.get_tag.outputs.TAG_NAME }}
          - Commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
